HackathonManager.AdminWebMvc/Controllers/MentorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HackathonManager.DTO;
using HackathonManager.PocoModels;
using HackathonManager.RepositoryPattern;


namespace HackathonManager.AdminWebMvc.Controllers
{
    public class MentorsController : Controller
    {
        private IRepository _repo = MvcApplication.DbRepo;
        private List<Mentor> _srndMentors;
        // GET: Mentors
        public ActionResult Index()
        {
            var mentors = _repo.All<Mentor>().ToList();

            var downloader = new HackathonManager.SrndResourcesManager.SrndMentorCsvDownloader();
            var parser = new HackathonManager.SrndMentorCsvParser();
            var newMentors = parser.Parse(downloader.GetCsv());
            _srndMentors = newMentors.Where(x => x.MentorType.ToLower().Trim() == "mentor").ToList();

            var areNewMentors = !_srndMentors.Except(mentors).Any();

            ViewBag.MentorsToPull = _srndMentors.Count();

            return View(mentors);
        }

        public ActionResult PullMentors()
        {
            var downloader = new HackathonManager.SrndResourcesManager.SrndMentorCsvDownloader();
            var parser = new HackathonManager.SrndMentorCsvParser();
            var result = parser.Parse(downloader.GetCsv());
            result = result.Where(x => x.MentorType.ToLower().Trim() == "mentor").ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult PullMentors(List<Mentor> pulledMentors)
        {
            foreach (var newMentor in pulledMentors)
            {
                _repo.Add<Mentor>(newMentor);
            }
            return RedirectToAction("Index");
        }

        // GET: Mentors/Create
        public ActionResult Create()
        {
            var mentor = new Mentor();
            return View(mentor);
        }

        // POST: Mentors/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mentors/Edit/5
        public ActionResult Edit(Guid id)
        {
            Mentor mentor;
            if (id == Guid.Empty)
                mentor = _repo.All<Mentor>().Where(x => x.GuidId == null).ToList().First();
            else
                mentor = _repo.All<Mentor>().Where(x => x.GuidId == id).ToList().First();

            return View(mentor);
        }

        // POST: Mentors/Edit/5
        [HttpPost]
        public ActionResult Edit(Mentor mentor)
        {
            try
            {
                // TODO: Add update logic here
                _repo.Delete<Mentor>(x => x.GuidId == mentor.GuidId);
                _repo.Add<Mentor>(mentor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Mentors/Delete/5
        [HttpPost]
        public ActionResult Delete(Mentor mentor)
        {
            try
            {
                // TODO: Add delete logic here
                _repo.Delete(mentor);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HackathonManager.AdminWebMvc/Views/Mentors/Create.cshtml
@model HackathonManager.DTO.Mentor
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            @using (Html.BeginForm("Edit", "Mentors", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Label(prop.PropertyName)
                        @Html.Editor(prop.PropertyName, new { attributes = new { @class = "form-control" } })
                    </div>
                }
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            }
        </div>
        <div class="col-lg-6">
            @using (Html.BeginForm("Delete", "Mentors", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Hidden(prop.PropertyName)
                    </div>
                }
                <input class="btn btn-danger" type="submit" value="Delete" />
            }
        </div>
    </div>
</div>

HackathonManager.AdminWebMvc/Views/Mentors/Edit.cshtml
@model HackathonManager.DTO.Mentor
@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.FirstName</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            @using (Html.BeginForm("Edit", "Mentors", FormMethod.Post, new { transaction = Model }))
    {
        foreach (var prop in ViewData.ModelMetadata.Properties)
        {
            <div class="form-group">
                @Html.Label(prop.PropertyName)
                @Html.Editor(prop.PropertyName, new { attributes = new { @class = "form-control" } })
            </div>
}
        <p>
            <input class="btn btn-primary" type="submit" value="Save" />
        </p>
}
        </div>
        <div class="col-lg-6">
            @using (Html.BeginForm("Delete", "Mentors", FormMethod.Post, new { transaction = Model }))
    {
        foreach (var prop in ViewData.ModelMetadata.Properties)
        {
            <div class="form-group">
                @Html.Hidden(prop.PropertyName)
            </div>
}
        <input class="btn btn-danger" type="submit" value="Delete" />
}
        </div>
    </div>
</div>

HackathonManager.AdminWebMvc/Views/Mentors/Index.cshtml
@model List<HackathonManager.DTO.Mentor>
@{
    ViewBag.Title = "Index";
    var properties = typeof(HackathonManager.DTO.Mentor).GetProperties();
}

<h2>Mentors</h2>

<p>Number of mentors: @Model.Count()</p>

<a class="btn btn-primary" href="/Mentors/Create">Add New</a>

<a class="btn btn-primary" href="/Mentors/PullMentors">@ViewBag.MentorsToPull New Mentors To Pull From SRND</a>

    @using (Html.BeginForm())
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <td></td>
                    @{
                        foreach (var property in properties)
                        {
                            <th>@property.Name</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var mentor in Model)
                    {
                        <tr>
                            <td><a class="btn btn-primary" href="/Mentors/Edit?id=@mentor.GuidId">Edit</a></td>
                            @foreach (var value in mentor.GetType().GetProperties())
                            {
                                <td>@value.GetValue(mentor, null)</td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    }

HackathonManager.AdminWebMvc/Views/Mentors/PullMentors.cshtml
@model List<HackathonManager.DTO.Mentor>
@{
    ViewBag.Title = "PullMentors";
    var properties = typeof(HackathonManager.DTO.Mentor).GetProperties();
}

<h2>Pull Mentors Srnd' "Clear" Backend</h2>
<br />
<h4>Entities Not Found In HackathonHandler Database: </h4>

@{
    if (Model != null)
    {
        using (Html.BeginForm("PullMentors", "Mentors", FormMethod.Post, new { transaction = Model }))
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        @{
                            foreach (var property in properties)
                            {
                                <th>@property.Name</th>
                            }
                        }
                    </tr>
                </thead>
                <tbody>
                    @{
                        for (int i = 0; i < Model.Count; i++)
                        {
                            @Html.HiddenFor(x => x[i].GuidId)
                            @Html.HiddenFor(x => x[i].FirstName)
                            @Html.HiddenFor(x => x[i].LastName)
                            @Html.HiddenFor(x => x[i].Email)
                            @Html.HiddenFor(x => x[i].Age)
                            @Html.HiddenFor(x => x[i].Event)
                             <tr>
                                @foreach (var value in Model[i].GetType().GetProperties())
                                {
                                    <td>@value.GetValue(Model[i], null)</td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <input class="btn btn-primary" type="submit" value="Pull Mentors" />
        }
    }
    else
    {
        <h2>No New Mentors To Pull</h2>
    }
}