HackathonManager.AdminWebMvc/Controllers/JudgesController.cs
using HackathonManager.RepositoryPattern;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HackathonManager.AdminWebMvc.Controllers
{
    public class JudgesController : Controller
    {
        private IRepository _repo = MvcApplication.DbRepo;

        // GET: Judges
        public ActionResult Index()
        {
            var judges = _repo.All<Judge>().ToList();

            return View(judges);
        }

        // GET: Judges/Create
        public ActionResult Create()
        {
            var judge = new Judge();
            return View(judge);
        }

        // POST: Judges/Create
        [HttpPost]
        public ActionResult Create(Judge judge)
        {
            try
            {
                // TODO: Add insert logic here
                _repo.Add<Judge>(judge);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Judges/Edit/5
        public ActionResult Edit(Guid id)
        {
            Judge judge;
            if (id == Guid.Empty)
                judge = _repo.All<Judge>().Where(x => x.GuidId == null).ToList().First();
            else
                judge = _repo.All<Judge>().Where(x => x.GuidId == id).ToList().First();

            return View(judge);
        }

        // POST: Judges/Edit/5
        [HttpPost]
        public ActionResult Edit(Judge judge)
        {
            try
            {
                // TODO: Add update logic here
                _repo.Delete<Judge>(x => x.GuidId == judge.GuidId);
                _repo.Add<Judge>(judge);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Judges/Delete/5
        [HttpPost]
        public ActionResult Delete(Judge judge)
        {
            try
            {
                // TODO: Add delete logic here
                _repo.Delete(judge);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HackathonManager.AdminWebMvc/Views/Judges/Create.cshtml
@model HackathonManager.Judge
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            @using (Html.BeginForm("Create", "Judges", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Label(prop.PropertyName)
                        @Html.Editor(prop.PropertyName, new { attributes = new { @class = "form-control" } })
                    </div>
                }
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            }
        </div>
        <div class="col-lg-6">
            @using (Html.BeginForm("Delete", "Judges", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Hidden(prop.PropertyName)
                    </div>
                }
                <input class="btn btn-danger" type="submit" value="Delete" />
            }
        </div>
    </div>
</div>

HackathonManager.AdminWebMvc/Views/Judges/Edit.cshtml
@model HackathonManager.Judge
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            @using (Html.BeginForm("Edit", "Judges", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Label(prop.PropertyName)
                        @Html.Editor(prop.PropertyName, new { attributes = new { @class = "form-control" } })
                    </div>
                }
                <p>
                    <input class="btn btn-primary" type="submit" value="Save" />
                </p>
            }
        </div>
        <div class="col-lg-6">
            @using (Html.BeginForm("Delete", "Judges", FormMethod.Post, new { transaction = Model }))
            {
                foreach (var prop in ViewData.ModelMetadata.Properties)
                {
                    <div class="form-group">
                        @Html.Hidden(prop.PropertyName)
                    </div>
                }
                <input class="btn btn-danger" type="submit" value="Delete" />
            }
        </div>
    </div>
</div>

HackathonManager.AdminWebMvc/Views/Judges/Index.cshtml
@model List<HackathonManager.Judge>
    @{
        ViewBag.Title = "Index";
        var properties = typeof(HackathonManager.Judge).GetProperties();
    }

    <h2>Judges</h2>

    <a class="btn btn-primary" href="/Judges/Create">Add New</a>

    @using (Html.BeginForm())
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <td></td>
                    @{
                        foreach (var property in properties)
                        {
                            <th>@property.Name</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var judge in Model)
                    {
                        <tr>
                            <td><a class="btn btn-primary" href="/Judges/Edit?id=@judge.GuidId">Edit</a></td>
                            @foreach (var value in judge.GetType().GetProperties())
                            {
                                <td>@value.GetValue(judge, null)</td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    }